package old;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The Issue class is a way of representing a JIRA issue or HPQC defect. 
 * You will notice I used the JIRA naming convention of calling things issues, instead of the HPQC Defect terminology.
 * For all practical purposes it doesn't matter, if you want to change the name back to Defect, I won't be upset.
 * 
 * The next part here does matter:
 * I used the HPQC field naming convention. In the static initialization section you will find where I initialize the field naming maps.
 * For example, in HPQC they use "name" the corresponding JIRA field is "summary".
 * 
 * If you want to add to the list of fields that are synced, you must update the following:
 * 1. JIRA_NAME_MAP - do another "put" where the key is the corresponding field in JIRA and the value is the field in HPQC
 * 2. HPQC_NAME_MAP - do another "put" where the key is the corresponding field in HPQC and the value is the field in JIRA
 * 		- It's basically the same thing just reversed.
 * 3. mSyncedFieldList - add the field name ( HPQC representation ) to the list.
 * 
 * Note: if the field is somewhat special, like the assignee field for JIRA or priority, then you need to check to make sure
 * that the field is being processed correctly in the Service class. 
 * - Specifically the convert methods.
 * 
 * 
 * Thanks for reading, you can get the author at:
 * @author Daniel Byrne - byrnedj12@gmail.com if he isn't in the corporate directory.
 *
 */
public class Issue
{

	private String mID;
	private String mJIRAKey;
	private Date mLastModified;
	private boolean mHasChanged;
	private boolean mAdded;
	
	//The fields we will sync are defined in mSyncedFieldList
	private Map<String, String> mSyncedFields;
	private String mJIRALinkKey;
	private boolean mLinkStatus;
	
	
	//Maps to keep fields straight
	public static Map<String, String> JIRA_NAME_MAP;
	public static Map<String, String> HPQC_NAME_MAP;
	public static List<String> mSyncedFieldList;

	//static initializers for the maps we use to find our way
	//TODO: This is a good place to read in config settings that we might get for different projects
	static 
	{
		//List of the currently synced fields.
		mSyncedFieldList = new ArrayList<String>();
		mSyncedFieldList.add( "description" );
		mSyncedFieldList.add( "name" );
		mSyncedFieldList.add( "status" );
		mSyncedFieldList.add( "detected-by" );
		mSyncedFieldList.add( "owner" );
		
		//KEY = JIRA FIELD NAME
		//VALUE = HPQC FIELD NAME
		JIRA_NAME_MAP = new HashMap<String,String>();
		JIRA_NAME_MAP.put( "reproducible", "reproducible");
		JIRA_NAME_MAP.put( "root-cause", "root-cause" );
		JIRA_NAME_MAP.put( "customfield_10609", "id");
		JIRA_NAME_MAP.put( "description", "description");
		JIRA_NAME_MAP.put( "priority", "priority" );
		JIRA_NAME_MAP.put( "dev-comments", "dev-comments" );
		JIRA_NAME_MAP.put( "summary", "name" );
		JIRA_NAME_MAP.put( "created", "creation-time" );
		JIRA_NAME_MAP.put( "updated", "last-modified" );
		JIRA_NAME_MAP.put( "customfield_10612", "status" );
		JIRA_NAME_MAP.put( "closing-date", "closing-date" );
		JIRA_NAME_MAP.put( "detected-in-rcyc", "detected-in-rcyc" );
		JIRA_NAME_MAP.put( "detected-in-rel", "detected-in-rel" );
		JIRA_NAME_MAP.put( "severity", "severity" );
		JIRA_NAME_MAP.put( "bug-ver-stamp", "bug-ver-stamp" );
		JIRA_NAME_MAP.put( "reporter", "detected-by");
		JIRA_NAME_MAP.put( "assignee", "owner");
		JIRA_NAME_MAP.put( "link-key", "user-01" );
		
		//KEY = HPQC FIELD NAME
		//VALUE = JIRA FIELD NAME
		HPQC_NAME_MAP = new HashMap<String,String>();
		HPQC_NAME_MAP.put( "reproducible","reproducible" );
		HPQC_NAME_MAP.put( "root-cause" ,"root-cause" );
		HPQC_NAME_MAP.put( "id", "customfield_10609" );
		HPQC_NAME_MAP.put( "description","description" );
		HPQC_NAME_MAP.put( "priority","priority");
		HPQC_NAME_MAP.put( "dev-comments" ,"dev-comments");
		HPQC_NAME_MAP.put( "name","summary");
		HPQC_NAME_MAP.put( "creation-time", "created");
		HPQC_NAME_MAP.put( "last-modified", "updated" );
		HPQC_NAME_MAP.put( "status", "customfield_10612" );
		HPQC_NAME_MAP.put( "closing-date", "closing date" );
		HPQC_NAME_MAP.put( "detected-in-rcyc", "detected-in-rcyc");
		HPQC_NAME_MAP.put( "detected-in-rel", "detected-in-rel" );
		HPQC_NAME_MAP.put( "severity", "severity" );
		HPQC_NAME_MAP.put( "bug-ver-stamp", "bug-ver-stamp");
		HPQC_NAME_MAP.put( "detected-by", "reporter");
		HPQC_NAME_MAP.put( "owner", "assignee");
		HPQC_NAME_MAP.put( "user-01", "link-key" );

	}

	/**
	 * Constructor - There are a few fields that aren't kept 'in sync' per say because the are permanent or changed automatically.
	 * mID = permanent, this is a unique id generated by HPQC, it would never be changed by JIRA
	 * mLastModified = when issues are updated via POST this time get updated.
	 * 
	 * Other fields:
	 * mAdded is used for knowing if this was a new issue added to JIRA
	 * mHasChanged is used to know if the field values were changed at all.
	 * @param aFields
	 */
	public Issue ( Map<String, String> aFields )
	{
		//Main ones that aren't being synced
		mID = aFields.get( "id" );
		mAdded = false;
		mHasChanged = false;
		mLinkStatus = false;
		
		SimpleDateFormat dateFormat = new SimpleDateFormat( "yyyy-MM-dd");
		//Last modified procedures for formatting times
		try
		{	
			if ( aFields.containsKey( "isJIRA" ) && aFields.get( "isJIRA" ).equals( "true" ) ) 
			{
				String toParse = aFields.get( "last-modified" );
				String left = toParse.substring( 0, toParse.indexOf( 'T' ) );
				String right = toParse.substring( toParse.indexOf( 'T' ) + 1, toParse.indexOf( '.' ) );
				toParse = left + " " + right;
				dateFormat = new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss" );
				mLastModified = dateFormat.parse( toParse  );
			}
			else
			{
				dateFormat = new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss" );
				mLastModified = dateFormat.parse( aFields.get( "last-modified" ) );
				mJIRALinkKey = aFields.get( "user-01" );
			}
		}
		catch( Exception e )
		{
			e.printStackTrace();
		}
		
		//Add the synced fields
		mSyncedFields = new HashMap<String, String>();
		for ( int i = 0; i < mSyncedFieldList.size(); i++ )
		{
			String key = mSyncedFieldList.get( i );
			String value = aFields.get( key );
			//put the key value pair into the map
			mSyncedFields.put( key, value );
		}
	}
	/**
	 * This is called on a new cycle so that we don't overlap what was added
	 */
	public void resetAdded()
	{
		mAdded = false;
	}
	/**
	 * This is called on a new cycle so that we don't overlap what was changed
	 */
	public void resetChanged()
	{
		mHasChanged = false;
	}

		
	/**
	 * Simple check for if the issue has changed
	 * @param aOldIssue to compare
	 * @return true if changed, false otherwise
	 */
	public boolean hasChanged()
	{
		return mHasChanged;
	}
	
	/**
	 * Set the issue to changed or not
	 * @param true if changed, false if not changed
	 */
	public void setChanged( boolean aChanged )
	{
		mHasChanged = aChanged;
	}
	
	/**
	 * Determines if the issue was added to the JIRA list.
	 * @return true if added, false otherwise
	 */
	public boolean wasAdded()
	{
		return mAdded;
	}
	
	/**
	 * Sets the added field, if the issue was added to the JIRA list
	 * @param true if added, false otherwise
	 */
	public void setAdded( boolean aAdded )
	{
		mAdded = aAdded;
	}
	
	/**
	 * Get last modified time of the issue
	 * @return the modified time and date
	 */
	public Date getLastModified()
	{
		return mLastModified;
	}

	/**
	 * Return the Id of the issue
	 * @return issue id
	 */
	public String getID()
	{
		return mID;
	}
	
	/**
	 * Sets the JIRA Issue key
	 * @param key, the JIRA Issue key
	 */
	public void setJIRAKey( String key )
	{
		mJIRAKey = key;
	}
	
	/**
	 * Returns the JIRA Issue key
	 * @return the JIRA Issue key
	 */
	public String getJIRAKey()
	{
		return mJIRAKey;
	}
	
	/**
	 * This is the map of the currently sync fields. Update mSyncedFields  and mSyncedFieldList for more fields
	 * @return a map of the fields being sync
	 */
	public Map<String, String> getSyncedFields()
	{
		return mSyncedFields;
	}
	
	/**
	 * Sets the fields in the synced field list if there are any changeds
	 * @param aNewValues
	 * @return true if anything changed
	 */
	public boolean setSyncedFields( Map<String, String> aNewValues )
	{
		boolean lChanged = false;
		
		for ( int i = 0; i < mSyncedFieldList.size(); i++ )
		{
			String fieldName = mSyncedFieldList.get( i );
			String currentFieldValue = mSyncedFields.get( fieldName );
			String newFieldValue = aNewValues.get( fieldName );
			
			//Null checks as we want to use blank values instead
			if ( currentFieldValue == null )
			{
				currentFieldValue = "";

			}
			if ( newFieldValue == null )
			{
				 newFieldValue = "";

			}
			
			//Set the new field value
			if ( !currentFieldValue.equals( newFieldValue ) )
			{
				System.out.println( "Changing issue " + this.getID() + ", " + fieldName + "'s value to: " + newFieldValue +
									", from: " + currentFieldValue );
				mSyncedFields.put( fieldName, newFieldValue );
				mHasChanged = true;
				lChanged = true;
			}
		}

		return lChanged;
	}
	public String getJIRALinkKey()
	{
		// TODO Auto-generated method stub
		return mJIRALinkKey;
	}
	public void setJIRALinkKey( String aJIRALinkKey )
	{
		mJIRALinkKey = aJIRALinkKey;
		
	}
	public void setLinkStatus( boolean aStatus )
	{
		mLinkStatus = true;
		
	}
	public boolean hasLink()
	{
		return mLinkStatus;
	}
}
